### PR TITLE
Fixing ticket #338

### LINKED ISSUE #338: Missing interface with 3.1.0
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.4.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.1.0 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.0.5 Symfony Sonata / Integrate Doctrine ORM into...
sonata-project/exporter                  1.7.0 Lightweight Exporter library

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower P...
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to l...
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to l...
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to l...
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to l...
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.9  The Symfony PHP framework


```

#### PHP version

```bash
$ php -v
PHP 5.6.25-1~dotdeb.7.1 (cli) (built: Aug 19 2016 03:15:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

## Steps to reproduce
1. Install sonata-core-bundle (3.1.0)
2. Don't install jms/serializer
3. Add to AppKernel.php
4. Launch the application

## Expected results
Application

## Actual results

```
PHP Fatal error:  Interface 'JMS\Serializer\Handler\SubscribingHandlerInterface' not found   
  in vendor/sonata-project/core-bundle/Serializer/SerializerHandlerInterface.php on line 20
```

#312 Causes the issue, by the new `SonataCoreExtension->configureSerializerFormats`.

## Stack trace

```
ClassNotFoundException in SerializerHandlerInterface.php line 20:
Attempted to load interface "SubscribingHandlerInterface" from namespace "JMS\Serializer\Handler".
Did you forget a "use" statement for another namespace?

1. in SerializerHandlerInterface.php line 20
2. in DebugClassLoader.php line 169
3. at DebugClassLoader->loadClass() in DebugClassLoader.php line 23
4. at spl_autoload_call() in DebugClassLoader.php line 23
5. in DebugClassLoader.php line 169
6. at DebugClassLoader->loadClass() in SonataCoreExtension.php line 164
7. at spl_autoload_call() in SonataCoreExtension.php line 164
8. at SonataCoreExtension->configureSerializerFormats() in SonataCoreExtension.php line 74
9. at SonataCoreExtension->load() in MergeExtensionConfigurationPass.php line 55
10. at MergeExtensionConfigurationPass->process() in MergeExtensionConfigurationPass.php line 39
11. at MergeExtensionConfigurationPass->process() in Compiler.php line 104
12. at Compiler->compile() in ContainerBuilder.php line 597
13. at ContainerBuilder->compile() in Kernel.php line 511
14. at Kernel->initializeContainer() in Kernel.php line 133
15. at Kernel->boot() in Kernel.php line 182
16. at Kernel->handle() in app_dev.php line 11
17. at {main}() in app_dev.php line 0
```

### PR DESCRIPTION
**Pull request by fracsi**
I am targetting this branch, because it is a bugfix for bug introduced in #312

Fixes #338

## Changelog

```markdown
### Fixed
- Added interface check for `JMS\Serializer\Handler\SubscribingHandlerInterface` in `SonataCoreExtension::configureSerializerFormats`
```

## Subject

Checking for `JMS\Serializer\Handler\SubscribingHandlerInterface` before configuring `BaseSerializerHandler`

### CODE REVIEW

**Comment by greg0ire** [comment]
I think we should also  trigger a deprecation warning if serialization options are used while the class is missing saying either : 

- an exception will be thrown in 4.0 if you configure these options if the package is not installed
- or the configuration options won't be available anymore in 4.0 if the package is not installed

**Comment by fracsi** [comment]
@greg0ire Can you add it to the PR? I will be unavailable for a week...

**Comment by greg0ire** [comment]
I can create my own PR based on yours, but I can't modify this one unless you grant me write access to your repo ;)

File: DependencyInjection/SonataCoreExtension.php [hunk 1]
```diff
@@ -52,6 +52,23 @@ public function load(array $configs, ContainerBuilder $container)
     {
         $processor = new Processor();
         $configuration = new Configuration();
+
+        if (!interface_exists('JMS\Serializer\Handler\SubscribingHandlerInterface')) {
```
Comment (OskarStark) [inline DependencyInjection/SonataCoreExtension.php]: NEXT_MAJOR missing

File: DependencyInjection/SonataCoreExtension.php [hunk 2]
```diff
@@ -161,7 +178,9 @@ public function registerFlashTypes(ContainerBuilder $container, array $config)
      */
     public function configureSerializerFormats($config)
     {
-        BaseSerializerHandler::setFormats($config['serializer']['formats']);
```
Comment (OskarStark) [inline DependencyInjection/SonataCoreExtension.php]: next major missing

Comment (greg0ire) [inline DependencyInjection/SonataCoreExtension.php]: There is nothing to do here on `NEXT_MAJOR`

**Comment by OskarStark** [comment]
LGTM 👍 

@greg0ire feel free to merge this PR

**Comment by greg0ire** [comment]
I'd like @fracsi to check it first, I didn't test it myself.

**Comment by fracsi** [comment]
@greg0ire LGTM

**Comment by greg0ire** [comment]
> @greg0ire LGTM

Did you test it locally though ?

**Comment by greg0ire** [comment]
What I mean is do you get a deprecation when and only when you configure the `sonata_core -> serializer` node ?

**Comment by fracsi** [comment]
@greg0ire I have tested it, with configured and not configured as well. 
Any hint when will it be tagged as released?

**Comment by greg0ire** [comment]
I'll merge #340 , then ask @Soullivaneuh for a release. But last one was 4 days ago :P

**Comment by fracsi** [comment]
@greg0ire Yeah i know. Maybe a patch release... :)

**Comment by pulzarraider** [comment]
@Soullivaneuh can you please release `3.1.1` with this change?

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataCoreBundle/releases/tag/3.1.1
