### PR TITLE
Fix deprecated events

### LINKED ISSUE #161: DEPRECATED - Constants PRE_BIND, BIND and POST_BIND
Hello.

I am updated my project from symfony 2.6 to 2.7 and after update i received this deprecated message:

DEPRECATED - Constants PRE_BIND, BIND and POST_BIND in class Symfony\Component\Form\FormEvents are deprecated since version 2.3 and will be removed in 3.0. Use PRE_SUBMIT, SUBMIT and POST_SUBMIT instead.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #161

### CODE REVIEW

File: Form/EventListener/ResizeFormListener.php [hunk 1]
```diff
@@ -63,8 +63,8 @@ public static function getSubscribedEvents()
     {
         return array(
             FormEvents::PRE_SET_DATA    => 'preSetData',
-            FormEvents::PRE_BIND        => 'preBind',
-            FormEvents::BIND            => 'onBind',
+            FormEvents::PRE_SUBMIT      => 'preSubmit',
```
Comment (rande) [inline Form/EventListener/ResizeFormListener.php]: I think I fix those code ... also you need to keep the original method name to avoid BC break

Comment (Soullivaneuh) [inline Form/EventListener/ResizeFormListener.php]: Seems not. :-)

Will take a look for BC.

Comment (Soullivaneuh) [inline Form/EventListener/ResizeFormListener.php]: Is BC really needed? Is this listener extended somewhere?

Comment (rande) [inline Form/EventListener/ResizeFormListener.php]: maybe is some people code, methods are public

Comment (Soullivaneuh) [inline Form/EventListener/ResizeFormListener.php]: Ok I'll do this.

Note: 
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/EventListener/FixCheckboxDataListener.php#L53

This BC trick will not works because `preSubmit` is called.

Do you want me to fix it?

Comment (rande) [inline Form/EventListener/ResizeFormListener.php]: We can also break the code and just add a note and raise an exception if thoses methods are called.

Comment (Soullivaneuh) [inline Form/EventListener/ResizeFormListener.php]: > just add a note

Agree.

> raise an exception if thoses methods are called.

Well, if people doesn't override subscribed events, old method will be **never** called.

**Comment by Soullivaneuh** [comment]
@rande Added a upgrade note.

File: Form/EventListener/ResizeFormListener.php (hunk 1 above)
Comment (Soullivaneuh) [inline Form/EventListener/ResizeFormListener.php]: I'll add a quick BC prevention.
